#!/usr/bin/env bash

if [ -z "${APPS}" ] || [ -z "${THRESHOLD_HOURS}"]; then
  echo "set environment variables APPS and THRESHOLD_HOURS"
  exit 0
fi

cutoffSeconds=$(date -d'now -${THRESHOLD_HOURS} hours' "+%s")
for app in ${APPS}; do
  redeploy=""
  creationTimestamps=$(kubectl get po --all-namespaces -l app=${app} -o jsonpath="{.items[*].metadata.creationTimestamp}")
  for creationTimestamp in ${creationTimestamps}; do
    creationSeconds=$(date -d'${creationTimestamp}' "+%s")
    if ["${creationSeconds}" -lt "${cutoffSeconds}"]; then
      redeploy="${redeploy}."
    fi
  done
  if [ ! -z ${redeploy} ]; then
    echo "Trigger redeployment of deployment ${app}"
    # from k8s 1.15, call kubectl rollout restart
    kubectl patch deployment ${app} -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"restarted\":\"$(date +%s)\"}}}}}" || true
  fi
done
