{{- define "userNames" }}
{{- printf "\"system:serviceaccount:%s:%s\"" .Values.namespace .Values.name -}}
{{- end }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-cluster-role-binding
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.name | quote }}
roleRef:
  kind: ClusterRole
  name: custom-cluster-role
subjects:
-
  kind: ServiceAccount
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
userNames:
- {{ template "userNames" . }}
